### PR TITLE
.gitignore and .editorconfig

### PR DESCRIPTION
**Pull request by tillig**
There was a lot of checked-in build output which was causing a clean build to be somewhat challenging. I've removed the build output and added a pretty standard .gitignore so it doesn't show up again.

I also added an .editorconfig to ensure things follow the formatting standards in your repo. I used one mostly based on the Roslyn repo's .editorconfig with minor updates to follow StyleCop/FxCop settings (should you choose to add Roslyn analyzers later). The only real divergence is the .cs files in this repo appear to be mostly tabs so I switched the C# indent type to tabs to ensure that's maintained.

Finally, the README was having some challenges when running through [Markdown lint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) so I updated some of the formatting there.

### CODE REVIEW

**Comment by DanielSSilva** [comment]
Does this PR already includes the changes referred on [this ](https://github.com/dotnet/coreclr/issues/22384) issue? Can't seem to find it

**Comment by tillig** [comment]
No, I wanted to keep "repo ops" separate from "code updates." They seemed peripherally related (in that, it'll help the seg fault stuff happen if I can make sure I'm not creating a whole bunch of merge conflicts and following your repo's guidelines) but like it's two separate "features" that implied two separate PRs.

**Comment by DanielSSilva** [comment]
PR was merged into master, I'll test it to check if everything went fine.
Thanks for the PR.
Can you open another with the correction of the seg fault?

**Comment by tillig** [comment]
It seems the bin and obj folders are still there under src which is a problem for merge conflicts and testing. If scripts or other items need to be there for testing, they should probably be part of a post-build copy step rather than checked in, right? So a clean checkout of the source yields a clean build environment? It looks like the .csproj has that set up. Should I re-delete the checked-in build output in my next PR?

**Comment by DanielSSilva** [comment]
weird that's still there. Maybe it's because when I merged, I forgot to delete bin and obj folders, so the ones that are there are the ones that were before. Later today I'll check that out and let you know.

**Pull request merged**
